### ISSUE TITLE
wheel support

### ISSUE THREAD

**Issue by ololoe** [dlitz/pycrypto#150]
http://pythonwheels.com/

If you add wheel support, windows users will be able to install pycrypto with simple `pip install pycrypto` without having a compiler.

**Comment by opalmer** [comment]
This should be possible if #116 is merged.

**Comment by ololoe** [comment]
Any chance it will be done? I see only your comments there.

**Comment by opalmer** [comment]
We'd have to ask @dlitz since he's the owner of this repository.  Code wise #116 is ready to go I think but it has not been reviewed yet.

As for pip/pypi, I'd be happy to upload wheels for Windows so everyone can benefit but I don't have access to do that.  I could also pass them to @dlitz to upload too if he'd rather not provide access (which I'd understand).

**Comment by sbonnick** [comment]
Curious if there is any update on getting pycrypto to use wheels? I use this library extensively on windows and it is a major pain point to always being finding and installing the native binaries. I am happy to help test or develop.

**Comment by ololoe** [comment]
`pip install pycryptodome`. Pycrypto is dead.
